resume_from_checkpoint_path: null # only used for resume_from_checkpoint option in PL
result_path: "./result"
pretrained_model_name_or_path: "/data/murayama/k8s/ocr_dxs1/donut/result/train_aii/20230403_165407"
dataset_name_or_paths: ["kie/health"] # loading datasets (from moldehub or path)
sort_json_key: True # cord dataset is preprocessed, and publicly available at https://huggingface.co/datasets/naver-clova-ix/cord-v2
train_batch_sizes: [2]
val_batch_sizes: [1]
input_size: [1600,1600] # when the input resolution differs from the pre-training setting, some weights will be newly initialized (but the model training would be okay)
max_length: 2500
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 3e-5
warmup_steps: 300 # 800/8*30/10, 10%
num_training_samples_per_epoch: 10119
max_epochs: 30
max_steps: -1
num_workers: 8
val_check_interval: 1.0
check_val_every_n_epoch: 3
gradient_clip_val: 1.0
verbose: True
window_size: 10
classes:
  - health
  - weight_0
  - weight_1
  - weight_2
  - waist_0
  - waist_1
  - waist_2
  - vfa_0
  - vfa_1
  - vfa_2
  - vc_rate_0
  - vc_rate_1
  - vc_rate_2
  - vc_0
  - vc_1
  - vc_2
  - urine_white_cell_0
  - urine_white_cell_1
  - urine_white_cell_2
  - urine_urobilinogen_0
  - urine_urobilinogen_1
  - urine_urobilinogen_2
  - urine_trans_epi_0
  - urine_trans_epi_1
  - urine_trans_epi_2
  - urine_red_cell_0
  - urine_red_cell_1
  - urine_red_cell_2
  - urine_protein_0
  - urine_protein_1
  - urine_protein_2
  - urine_protein_v_0
  - urine_protein_v_1
  - urine_protein_v_2
  - urine_ph_0
  - urine_ph_1
  - urine_ph_2
  - urine_ketone_0
  - urine_ketone_1
  - urine_ketone_2
  - urine_hyaline_0
  - urine_hyaline_1
  - urine_hyaline_2
  - urine_gravity_0
  - urine_gravity_1
  - urine_gravity_2
  - urine_granular_0
  - urine_granular_1
  - urine_granular_2
  - urine_glucose_0
  - urine_glucose_1
  - urine_glucose_2
  - urine_glucose_v_0
  - urine_glucose_v_1
  - urine_glucose_v_2
  - urine_epi_cell_0
  - urine_epi_cell_1
  - urine_epi_cell_2
  - urine_epi_0
  - urine_epi_1
  - urine_epi_2
  - urine_cast_0
  - urine_cast_1
  - urine_cast_2
  - urine_blood_0
  - urine_blood_1
  - urine_blood_2
  - urine_bilirubin_0
  - urine_bilirubin_1
  - urine_bilirubin_2
  - urine_bacteria_0
  - urine_bacteria_1
  - urine_bacteria_2
  - urine_albumin_v_0
  - urine_albumin_v_1
  - urine_albumin_v_2
  - urine_albumin_rate_0
  - urine_albumin_rate_1
  - urine_albumin_rate_2
  - urine_albumin1d_0
  - urine_albumin1d_1
  - urine_albumin1d_2
  - uric_acid_0
  - uric_acid_1
  - uric_acid_2
  - uibc_0
  - uibc_1
  - uibc_2
  - tumor_scc_0
  - tumor_scc_1
  - tumor_scc_2
  - tumor_psa_0
  - tumor_psa_1
  - tumor_psa_2
  - tumor_pap_0
  - tumor_pap_1
  - tumor_pap_2
  - tumor_nse_0
  - tumor_nse_1
  - tumor_nse_2
  - tumor_cyfpra_0
  - tumor_cyfpra_1
  - tumor_cyfpra_2
  - tumor_cea_0
  - tumor_cea_1
  - tumor_cea_2
  - tumor_ca199_0
  - tumor_ca199_1
  - tumor_ca199_2
  - tumor_ca153_0
  - tumor_ca153_1
  - tumor_ca153_2
  - tumor_ca125_0
  - tumor_ca125_1
  - tumor_ca125_2
  - tumor_afp_class_0
  - tumor_afp_class_1
  - tumor_afp_class_2
  - tumor_afp_0
  - tumor_afp_1
  - tumor_afp_2
  - tubular_epi_0
  - tubular_epi_1
  - tubular_epi_2
  - tsh_0
  - tsh_1
  - tsh_2
  - total_diagnosis_0
  - total_diagnosis_1
  - total_diagnosis_2
  - tibc_0
  - tibc_1
  - tibc_2
  - stomach_xray_0
  - stomach_xray_1
  - stomach_xray_2
  - egd_0
  - egd_1
  - egd_2
  - stomach_echo_0
  - stomach_echo_1
  - stomach_echo_2
  - hypogastric_echo_0
  - hypogastric_echo_1
  - hypogastric_echo_2
  - std_weight_0
  - std_weight_1
  - std_weight_2
  - sputum_cytology_0
  - sputum_cytology_1
  - sputum_cytology_2
  - sera_tpha_0
  - sera_tpha_1
  - sera_tpha_2
  - sera_sts_0
  - sera_sts_1
  - sera_sts_2
  - sera_rpr_0
  - sera_rpr_1
  - sera_rpr_2
  - sera_rf_0
  - sera_rf_1
  - sera_rf_2
  - sera_ra_0
  - sera_ra_1
  - sera_ra_2
  - sera_glass_test_0
  - sera_glass_test_1
  - sera_glass_test_2
  - sera_ferritin_0
  - sera_ferritin_1
  - sera_ferritin_2
  - sera_esr_1_0
  - sera_esr_1_1
  - sera_esr_1_2
  - sera_esr_2_0
  - sera_esr_2_1
  - sera_esr_2_2
  - sera_cpk_0
  - sera_cpk_1
  - sera_cpk_2
  - sera_aso_0
  - sera_aso_1
  - sera_aso_2
  - sera_aggregation_0
  - sera_aggregation_1
  - sera_aggregation_2
  - rectal_exam_0
  - rectal_exam_1
  - rectal_exam_2
  - rational_symptom_0
  - rational_symptom_1
  - rational_symptom_2
  - pvc_0
  - pvc_1
  - pvc_2
  - pulse_wave_count_0
  - pulse_wave_count_1
  - pulse_wave_count_2
  - prostate_exam_0
  - prostate_exam_1
  - prostate_exam_2
  - prostate_echo_0
  - prostate_echo_1
  - prostate_echo_2
  - ponderal_index_0
  - ponderal_index_1
  - ponderal_index_2
  - pg2_0
  - pg2_1
  - pg2_2
  - pg2_d_0
  - pg2_d_1
  - pg2_d_2
  - pg1_0
  - pg1_1
  - pg1_2
  - pef_0
  - pef_1
  - pef_2
  - pancreas_amylase_0
  - pancreas_amylase_1
  - pancreas_amylase_2
  - objective_symptom_0
  - objective_symptom_1
  - objective_symptom_2
  - ntpro_bnp_0
  - ntpro_bnp_1
  - ntpro_bnp_2
  - metabo_triglyceride_0
  - metabo_triglyceride_1
  - metabo_triglyceride_2
  - metabo_tcholesterol_0
  - metabo_tcholesterol_1
  - metabo_tcholesterol_2
  - metabo_nhdl_0
  - metabo_nhdl_1
  - metabo_nhdl_2
  - metabo_ldl_0
  - metabo_ldl_1
  - metabo_ldl_2
  - metabo_hdl_0
  - metabo_hdl_1
  - metabo_hdl_2
  - metabo_blipo_0
  - metabo_blipo_1
  - metabo_blipo_2
  - medical_history_0
  - medical_history_1
  - medical_history_2
  - medical_finding_0
  - medical_finding_1
  - medical_finding_2
  - liver_ztt_0
  - liver_ztt_1
  - liver_ztt_2
  - liver_ttt_0
  - liver_ttt_1
  - liver_ttt_2
  - liver_tp_0
  - liver_tp_1
  - liver_tp_2
  - liver_ldh_0
  - liver_ldh_1
  - liver_ldh_2
  - liver_lap_0
  - liver_lap_1
  - liver_lap_2
  - liver_antibody_c_0
  - liver_antibody_c_1
  - liver_antibody_c_2
  - liver_antibody_q_0
  - liver_antibody_q_1
  - liver_antibody_q_2
  - liver_antigen_0
  - liver_antigen_1
  - liver_antigen_2
  - liver_antibody_0
  - liver_antibody_1
  - liver_antibody_2
  - liver_antigen_q_0
  - liver_antigen_q_1
  - liver_antigen_q_2
  - liver_ggtp_0
  - liver_ggtp_1
  - liver_ggtp_2
  - liver_che_ul_0
  - liver_che_ul_1
  - liver_che_ul_2
  - liver_che_iul_0
  - liver_che_iul_1
  - liver_che_iul_2
  - liver_tbil_0
  - liver_tbil_1
  - liver_tbil_2
  - liver_dbil_0
  - liver_dbil_1
  - liver_dbil_2
  - liver_ibil_0
  - liver_ibil_1
  - liver_ibil_2
  - liver_ibil_d_0
  - liver_ibil_d_1
  - liver_ibil_d_2
  - liver_ast_0
  - liver_ast_1
  - liver_ast_2
  - liver_antibody_a_0
  - liver_antibody_a_1
  - liver_antibody_a_2
  - liver_alt_0
  - liver_alt_1
  - liver_alt_2
  - liver_alp_0
  - liver_alp_1
  - liver_alp_2
  - liver_albumin_0
  - liver_albumin_1
  - liver_albumin_2
  - liver_ag_0
  - liver_ag_1
  - liver_ag_2
  - last_2_0
  - last_2_1
  - last_2_2
  - last_1_0
  - last_1_1
  - last_1_2
  - kidney_egfr_0
  - kidney_egfr_1
  - kidney_egfr_2
  - kidney_crp_0
  - kidney_crp_1
  - kidney_crp_2
  - sera_crp_0
  - sera_crp_1
  - sera_crp_2
  - kidney_creatinine_0
  - kidney_creatinine_1
  - kidney_creatinine_2
  - kidney_bun_0
  - kidney_bun_1
  - kidney_bun_2
  - job_history_0
  - job_history_1
  - job_history_2
  - iop_r_0
  - iop_r_1
  - iop_r_2
  - iop_l_0
  - iop_l_1
  - iop_l_2
  - institution_name_0
  - institution_name_1
  - institution_name_2
  - inorganic_phosphorus_0
  - inorganic_phosphorus_1
  - inorganic_phosphorus_2
  - hpilori_antibody_0
  - hpilori_antibody_1
  - hpilori_antibody_2
  - hpiloli_class_0
  - hpiloli_class_1
  - hpiloli_class_2
  - hemoto_platelet_0
  - hemoto_platelet_1
  - hemoto_platelet_2
  - hemato_wbc_0
  - hemato_wbc_1
  - hemato_wbc_2
  - hemato_stab_0
  - hemato_stab_1
  - hemato_stab_2
  - hemato_seg_0
  - hemato_seg_1
  - hemato_seg_2
  - hemato_rbc_0
  - hemato_rbc_1
  - hemato_rbc_2
  - hemato_neutrophil_0
  - hemato_neutrophil_1
  - hemato_neutrophil_2
  - hemato_monocyte_0
  - hemato_monocyte_1
  - hemato_monocyte_2
  - hemato_mcv_0
  - hemato_mcv_1
  - hemato_mcv_2
  - hemato_mchc_0
  - hemato_mchc_1
  - hemato_mchc_2
  - hemato_mch_0
  - hemato_mch_1
  - hemato_mch_2
  - hemato_lymphocyte_0
  - hemato_lymphocyte_1
  - hemato_lymphocyte_2
  - hemato_hemoglobin_0
  - hemato_hemoglobin_1
  - hemato_hemoglobin_2
  - hemato_hematocrit_0
  - hemato_hematocrit_1
  - hemato_hematocrit_2
  - hemato_fe_0
  - hemato_fe_1
  - hemato_fe_2
  - hemato_eosinocyte_0
  - hemato_eosinocyte_1
  - hemato_eosinocyte_2
  - hemato_bosocyte_0
  - hemato_bosocyte_1
  - hemato_bosocyte_2
  - height_0
  - height_1
  - height_2
  - hearing_r_0
  - hearing_r_1
  - hearing_r_2
  - hearing_l_0
  - hearing_l_1
  - hearing_l_2
  - hearing_1000_r_0
  - hearing_1000_r_1
  - hearing_1000_r_2
  - hearing_1000_l_0
  - hearing_1000_l_1
  - hearing_1000_l_2
  - hearing_4000_r_0
  - hearing_4000_r_1
  - hearing_4000_r_2
  - hearing_4000_l_0
  - hearing_4000_l_1
  - hearing_4000_l_2
  - hearing_250_r_0
  - hearing_250_r_1
  - hearing_250_r_2
  - hearing_8000_r_0
  - hearing_8000_r_1
  - hearing_8000_r_2
  - hearing_250_l_0
  - hearing_250_l_1
  - hearing_250_l_2
  - hearing_8000_l_0
  - hearing_8000_l_1
  - hearing_8000_l_2
  - gp_class_0
  - gp_class_1
  - gp_class_2
  - gg_fraction_0
  - gg_fraction_1
  - gg_fraction_2
  - ft4_0
  - ft4_1
  - ft4_2
  - ft3_0
  - ft3_1
  - ft3_2
  - fev1_rate_rate_0
  - fev1_rate_rate_1
  - fev1_rate_rate_2
  - fev1_rate_0
  - fev1_rate_1
  - fev1_rate_2
  - fev1_0
  - fev1_1
  - fev1_2
  - fev_rate_0
  - fev_rate_1
  - fev_rate_2
  - fev_0
  - fev_1
  - fev_2
  - fecal_blood_1_0
  - fecal_blood_1_1
  - fecal_blood_1_2
  - fecal_blood_2_0
  - fecal_blood_2_1
  - fecal_blood_2_2
  - fat_ratio_0
  - fat_ratio_1
  - fat_ratio_2
  - kw_r_0
  - kw_r_1
  - kw_r_2
  - kw_fr_0
  - kw_fr_1
  - kw_fr_2
  - kw_l_0
  - kw_l_1
  - kw_l_2
  - kw_fl_0
  - kw_fl_1
  - kw_fl_2
  - scheie_h_r_0
  - scheie_h_r_1
  - scheie_h_r_2
  - scheie_h_fr_0
  - scheie_h_fr_1
  - scheie_h_fr_2
  - scheie_h_l_0
  - scheie_h_l_1
  - scheie_h_l_2
  - scheie_h_fl_0
  - scheie_h_fl_1
  - scheie_h_fl_2
  - scheie_s_r_0
  - scheie_s_r_1
  - scheie_s_r_2
  - scheie_s_fr_0
  - scheie_s_fr_1
  - scheie_s_fr_2
  - scheie_s_l_0
  - scheie_s_l_1
  - scheie_s_l_2
  - scheie_s_fl_0
  - scheie_s_fl_1
  - scheie_s_fl_2
  - scott_r_0
  - scott_r_1
  - scott_r_2
  - scott_fr_0
  - scott_fr_1
  - scott_fr_2
  - scott_l_0
  - scott_l_1
  - scott_l_2
  - scott_fl_0
  - scott_fl_1
  - scott_fl_2
  - wm_r_0
  - wm_r_1
  - wm_r_2
  - wm_fr_0
  - wm_fr_1
  - wm_fr_2
  - wm_l_0
  - wm_l_1
  - wm_l_2
  - wm_fl_0
  - wm_fl_1
  - wm_fl_2
  - davis_r_0
  - davis_r_1
  - davis_r_2
  - davis_fr_0
  - davis_fr_1
  - davis_fr_2
  - davis_l_0
  - davis_l_1
  - davis_l_2
  - davis_fl_0
  - davis_fl_1
  - davis_fl_2
  - eyeground_fr_0
  - eyeground_fr_1
  - eyeground_fr_2
  - eyeground_fl_0
  - eyeground_fl_1
  - eyeground_fl_2
  - eye_sight_r_0
  - eye_sight_r_1
  - eye_sight_r_2
  - eye_sight_l_0
  - eye_sight_l_1
  - eye_sight_l_2
  - eye_sight_cr_0
  - eye_sight_cr_1
  - eye_sight_cr_2
  - eye_sight_cl_0
  - eye_sight_cl_1
  - eye_sight_cl_2
  - exmaminee_dob_0
  - exmaminee_dob_1
  - exmaminee_dob_2
  - examinee_name_kana_0
  - examinee_name_kana_1
  - examinee_name_kana_2
  - examinee_name_0
  - examinee_name_1
  - examinee_name_2
  - examinee_gender_0
  - examinee_gender_1
  - examinee_gender_2
  - exam_date_0
  - exam_date_1
  - exam_date_2
  - epi_cast_0
  - epi_cast_1
  - epi_cast_2
  - electro_na_0
  - electro_na_1
  - electro_na_2
  - electro_k_0
  - electro_k_1
  - electro_k_2
  - electro_cl_0
  - electro_cl_1
  - electro_cl_2
  - electro_ca_0
  - electro_ca_1
  - electro_ca_2
  - echocardiogram_0
  - echocardiogram_1
  - echocardiogram_2
  - ecg_rest_0
  - ecg_rest_1
  - ecg_rest_2
  - ecg_load_0
  - ecg_load_1
  - ecg_load_2
  - ecg_holter_0
  - ecg_holter_1
  - ecg_holter_2
  - doctor_name_0
  - doctor_name_1
  - doctor_name_2
  - diabetic_insulin_0
  - diabetic_insulin_1
  - diabetic_insulin_2
  - diabetic_homar_0
  - diabetic_homar_1
  - diabetic_homar_2
  - diabetic_hba1c_jds_0
  - diabetic_hba1c_jds_1
  - diabetic_hba1c_jds_2
  - diabetic_hba1c_ngsp_0
  - diabetic_hba1c_ngsp_1
  - diabetic_hba1c_ngsp_2
  - diabetic_fructosamine_0
  - diabetic_fructosamine_1
  - diabetic_fructosamine_2
  - diabetic_fbg_0
  - diabetic_fbg_1
  - diabetic_fbg_2
  - diabetic_cbg_0
  - diabetic_cbg_1
  - diabetic_cbg_2
  - blood_sugar_0_0
  - blood_sugar_0_1
  - blood_sugar_0_2
  - blood_sugar_1_0
  - blood_sugar_1_1
  - blood_sugar_1_2
  - blood_sugar_2_0
  - blood_sugar_2_1
  - blood_sugar_2_2
  - current_0
  - current_1
  - current_2
  - course_name_0
  - course_name_1
  - course_name_2
  - consul_1_0
  - consul_1_1
  - consul_1_2
  - consul_2_0
  - consul_2_1
  - consul_2_2
  - consul_3_0
  - consul_3_1
  - consul_3_2
  - consul_4_0
  - consul_4_1
  - consul_4_2
  - consul_5_0
  - consul_5_1
  - consul_5_2
  - consul_6_0
  - consul_6_1
  - consul_6_2
  - consul_7_0
  - consul_7_1
  - consul_7_2
  - consul_8_0
  - consul_8_1
  - consul_8_2
  - consul_9_0
  - consul_9_1
  - consul_9_2
  - consul_10_0
  - consul_10_1
  - consul_10_2
  - consul_11_0
  - consul_11_1
  - consul_11_2
  - consul_12_0
  - consul_12_1
  - consul_12_2
  - consul_13_0
  - consul_13_1
  - consul_13_2
  - consul_14_0
  - consul_14_1
  - consul_14_2
  - consul_15_0
  - consul_15_1
  - consul_15_2
  - consul_16_0
  - consul_16_1
  - consul_16_2
  - consul_17_0
  - consul_17_1
  - consul_17_2
  - consul_18_0
  - consul_18_1
  - consul_18_2
  - consul_19_0
  - consul_19_1
  - consul_19_2
  - consul_20_0
  - consul_20_1
  - consul_20_2
  - consul_21_0
  - consul_21_1
  - consul_21_2
  - consul_22_0
  - consul_22_1
  - consul_22_2
  - consul_metabo_0
  - consul_metabo_1
  - consul_metabo_2
  - consul_weight_0
  - consul_weight_1
  - consul_weight_2
  - consul_dental_0
  - consul_dental_1
  - consul_dental_2
  - colonoscope_0
  - colonoscope_1
  - colonoscope_2
  - chest_xray_0
  - chest_xray_1
  - chest_xray_2
  - chest_ct_0
  - chest_ct_1
  - chest_ct_2
  - cervical_class_0
  - cervical_class_1
  - cervical_class_2
  - cervical_class_f_0
  - cervical_class_f_1
  - cervical_class_f_2
  - cervical_bethesda_0
  - cervical_bethesda_1
  - cervical_bethesda_2
  - cervical_bethesda_f_0
  - cervical_bethesda_f_1
  - cervical_bethesda_f_2
  - uterine_corpus_0
  - uterine_corpus_1
  - uterine_corpus_2
  - cervical_cytology_0
  - cervical_cytology_1
  - cervical_cytology_2
  - gynecology_echo_0
  - gynecology_echo_1
  - gynecology_echo_2
  - gynecology_exam_0
  - gynecology_exam_1
  - gynecology_exam_2
  - certificate_number_0
  - certificate_number_1
  - certificate_number_2
  - celebral_mri_0
  - celebral_mri_1
  - celebral_mri_2
  - celebral_mra_0
  - celebral_mra_1
  - celebral_mra_2
  - celebral_other_0
  - celebral_other_1
  - celebral_other_2
  - cavi_0
  - cavi_1
  - cavi_2
  - card_sign_0
  - card_sign_1
  - card_sign_2
  - card_number_0
  - card_number_1
  - card_number_2
  - calcium_exalate_0
  - calcium_exalate_1
  - calcium_exalate_2
  - btype_abo_0
  - btype_abo_1
  - btype_abo_2
  - btype_rh_0
  - btype_rh_1
  - btype_rh_2
  - breast_exam_0
  - breast_exam_1
  - breast_exam_2
  - breast_echo_0
  - breast_echo_1
  - breast_echo_2
  - mammography_0
  - mammography_1
  - mammography_2
  - mammography_r_0
  - mammography_r_1
  - mammography_r_2
  - mammography_l_0
  - mammography_l_1
  - mammography_l_2
  - breast_finding_0
  - breast_finding_1
  - breast_finding_2
  - bone_density_0
  - bone_density_1
  - bone_density_2
  - bmi_0
  - bmi_1
  - bmi_2
  - bp_systolic_0
  - bp_systolic_1
  - bp_systolic_2
  - bp_diastolic_0
  - bp_diastolic_1
  - bp_diastolic_2
  - bp_systolic_2_0
  - bp_systolic_2_1
  - bp_systolic_2_2
  - bp_diastolic_2_0
  - bp_diastolic_2_1
  - bp_diastolic_2_2
  - bg_fraction_0
  - bg_fraction_1
  - bg_fraction_2
  - bapwv_0
  - bapwv_1
  - bapwv_2
  - arteria_echo_0
  - arteria_echo_1
  - arteria_echo_2
  - alb_fraction_0
  - alb_fraction_1
  - alb_fraction_2
  - a2g_fraction_0
  - a2g_fraction_1
  - a2g_fraction_2
  - a1g_fraction_0
  - a1g_fraction_1
  - a1g_fraction_2